apiVersion: v2
name: signoz-observability
version: 0.1.0
description: >
  A Helm chart to deploy SigNoz with OpenTelemetry collectors for monitoring Windows/Linux VMs, 
  Kubernetes clusters, and databases across Oracle and GCP cloud environments.

  This chart also integrates with a ClickHouse cluster managed using the Altinity ClickHouse Operator for HA or POC setups.
type: application

dependencies:
  - name: signoz
    version: 0.26.2
    repository: https://charts.signoz.io
  - name: opentelemetry-collector
    version: 0.73.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: clickhouse
    alias: clickhouse-cluster
    version: 0.1.0
    repository: https://altinity.github.io/helm-charts
